export * from './FormIncident/FormIncident';
export * from './Registro/Registro';
export * from './SearchBar/SearchBar';
export * from './DisplayEdit/DisplayEdit';
export * from './DetalleRegistro/DetalleRegistro';
export * from './FilterByState/FilterByState';
export * from './IncidentsTable/IncidentsTable';
export * from './StateColor/StateColor';
export * from './FloatingButton/FloatingButton';